apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: originate

resources:
  - deployment.yaml

generatorOptions:
  labels:
    app.kubernetes.io/name: decision-service
    app.kubernetes.io/part-of: originate
