apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: originate

resources:
  - deployment.yaml
  - status-snapshot-cronjob.yaml

configMapGenerator:
  - name: loan-service-config
    literals:
      - CUSTOMER_SERVICE_URL=http://customer-service:8081
      - PRODUCT_SERVICE_URL=http://product-service:8083
      - DECISION_SERVICE_URL=http://decision-service:8084
      - CORS_ALLOWED_ORIGIN=http://34.142.232.167:30080
      - DEMO_ERROR_ENABLED=false
      - DEMO_BIGDECIMAL_ERROR_ENABLED=true

generatorOptions:
  labels:
    app.kubernetes.io/name: loan-service
    app.kubernetes.io/part-of: originate
