apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
configMapGenerator:
  - name: loan-service-config
    literals:
      - PAYMENT_PROVIDER_API_PATH=/v1/disbursements
