apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: customer-service
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: originate
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/soitcommittee/originate.git
    targetRevision: main
    path: k8s/apps/customer-service
  destination:
    server: https://kubernetes.default.svc
    namespace: originate
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
  revisionHistoryLimit: 5
