apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-service
  labels:
    app.kubernetes.io/name: notification-service
    app.kubernetes.io/part-of: originate
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: notification-service-log-reader
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - pods/log
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: notification-service-log-reader
subjects:
  - kind: ServiceAccount
    name: notification-service
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: notification-service-log-reader
