apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: originate

resources:
  - deployment.yaml

configMapGenerator:
  - name: customer-service-config
    literals:
      - CORS_ALLOWED_ORIGIN=http://34.142.232.167:30080

generatorOptions:
  labels:
    app.kubernetes.io/name: customer-service
    app.kubernetes.io/part-of: originate
