apiVersion: v1
kind: ConfigMap
metadata:
  name: originate-config
  labels:
    app.kubernetes.io/part-of: originate
data:
  CUSTOMER_SERVICE_URL: http://customer-service:8081
  CORS_ALLOWED_ORIGIN: http://localhost:3000
  DEMO_ERROR_ENABLED: "false"

