spring.application.name=payment-provider
server.port=${SERVER_PORT:8090}

management.endpoints.web.exposure.include=health,info,prometheus
management.metrics.tags.service=${spring.application.name}
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true

logging.pattern.console=%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} level=%-5level service=${spring.application.name} requestId=%X{requestId:-none} thread=%thread logger=%logger{36} message=%msg%n%ex
